### ISSUE TITLE
docs on Google Chrome (Mac) are unusable

### ISSUE THREAD

**Issue by amargonis** [Teradata/quickstarts#108]
Docs on google chrome cause multiple unexpected errors
1) Extremely high CPU utilization
2) scrolling through the documentation resets the scroll position back to the top or up.  That is, there is no smooth scrolling and often you can never get to and fully read the documentation because it will reset the scroll location
3) Clicking the outline does not position properly to the documentation.  I believe this is a result of the above mentioned scroll issue.

This has been true for 1+ years and the new changes to docs make it much worse.

**Comment by adamtwo** [comment]
Hi @amargonis, yes, we are aware of issue number 3 and are working to resolve it. As to high CPU utilization and scroll resets, we have not observed it. I'm on a Mac and I use Chrome to browse the website several times a day. 

Do you mind doing a quick test? Could you please try the website out in the Incognito mode and see if you still see issues 1 and 2?

thanks,
Adam

**Comment by adamtwo** [comment]
We have fixed all the outstanding issues with the layout. We have not noticed any performance issues. If you still experience issues please open another issue.
