### ISSUE TITLE
New Password Issues

### ISSUE THREAD

**Issue by nkuruvil** [Teradata/quickstarts#2]
I am trying to use Teradata Vantage. However, it is requiring me to use a new password, and every attempt to input a new password fails. It says it is a bad password but does not tells me what qualifies as a good password. What are the criteria for an acceptable password?

![image](https://user-images.githubusercontent.com/23100720/137775351-8cb7e204-3ead-4de2-91b7-d1245b3f94c2.png)

**Comment by aedocw** [comment]
The download page for Vantage Express (https://downloads.teradata.com/download/database/teradata-express-for-vmware-player) includes a link at the bottom for support, directing users to https://support.teradata.com/community?id=community_forum&sys_id=8d780fb91b429010919cc8866e4bcb50 if they have any issues with that image.
