### ISSUE TITLE
Geospatial how to

### ISSUE THREAD

**Issue by Pibbers** [Teradata/quickstarts#23]
Idea for an additional how to demo on the use geospatial data perhaps as part of a 4D analytics series of demos?

**Comment by jmacagno** [comment]
Thank you Paul for your input.

**Comment by adamtwo** [comment]
We now offer an extensive set of examples using geospatial functions in ClearScape Analytics Experience:


![image](https://github.com/Teradata/quickstarts/assets/6579240/d72c8f26-259c-4c81-84d5-3181d745cbd1)
