### ISSUE TITLE
Vantage Express VirtualBox installation script issues

### ISSUE THREAD

**Issue by 233194** [Teradata/quickstarts#27]
I tried to install VE on VirtualBox following the instructions on this page. Unfortunately I ran into issues in the installation script:

1.) **script fails with errors** if file name or file path of the downloaded VB disk files contains blanks --> quotes are missing in script for these expressions: `"$($disk1.FullName)`"" in the installer script located on Github

2.) Installs virtual machine with "Vantage Express 17.10" name although downloaded version 17.20. Confusing for the user.

**Comment by adamtwo** [comment]
Hi,
Thanks for your comments. I've updated the script. It now quotes file paths to disk files. It no longer adds a version to the VM name.

thanks,
Adam

**Comment by 233194** [comment]
Thanks for incorporating above updated string quoting's. PowerShell script worked now with blanks in the file path too.
