### ISSUE TITLE
Vantage Express Database not starting in VM on VirtualBox

### ISSUE THREAD

**Issue by 233194** [Teradata/quickstarts#28]
Running the install script on this page does not complete. 
Installation script stays forever with the following message shown on the PowerShell terminal screen:

Waiting for VM "Vantage Express 17.20" to power on...
VM "Vantage Express 17.20" has been successfully started.
*** VM disks attached
Attempting to ssh into the vm. Attempt 1. This might take a minute.
powershell : kex_exchange_identification: read: Connection reset
At line:1 char:1
+ powershell -ExecutionPolicy Bypass -File imageinstall.ps1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (kex_exchange_id...onnection reset:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Waiting 10 seconds before the next attempt.
Attempting to ssh into the vm. Attempt 2. This might take a minute.
This system is only for the use of authorized users.
Access may be monitored or recorded for security
purposes.

**Comment by adamtwo** [comment]
Hi,
The verbiage that you pasted at the end of the ticket indicates that the machine has started successfully. It might be waiting on you to enter the password (which is 'root').

Adam

**Comment by 233194** [comment]
Thanks for providing the updated Vantage Express VM image for download. It fixed the issue. Installation using the PowerShell script and the new VM image worked very well!
