### ISSUE TITLE
[azure deploy] ssh to port 4422 hang

### ISSUE THREAD

**Issue by davidkhala** [Teradata/quickstarts#42]
https://quickstarts.teradata.com/run-vantage-express-on-microsoft-azure.html

When we reach step 
```
ssh -p 4422 root@localhost
```
it hangs until get error
```
kex_exchange_identification: read: Connection reset by peer
Connection reset by 127.0.0.1 port 4422
```

**Comment by adamtwo** [comment]
This is an old issue, but commenting just in case it helps future users. We currently offer free, small, disposable Vantage instances in the cloud at https://clearscape.teradata.com/. 
If you still want to run Vantage Express yourself it's still possible. When you go through the steps, make sure you try multiple times. It takes a while to start the nested VM. As the nested VM boots up, it may terminate the connection until the ssh server is ready to accept requests.
